env: dev

app_project: applike
app_family: justtrack
app_group: justdev
app_name: kinesis-admin

cloud:
  aws:
    defaults:
      credentials:
        access_key_id: justtrack
        secret_access_key: justtrack
      endpoint: http://localhost:4566
      region: eu-central-1

httpserver:
  default:
    port: 8080
    mode: release
